ALTER TABLE `idm_console_codepackage`   
  CHANGE `CLASSNAME` `CLASSNAME` VARCHAR(200) CHARSET utf8 COLLATE utf8_bin NOT NULL   COMMENT '代码包名', 
  ADD PRIMARY KEY (`id`),
  ADD  INDEX `PRIMARY_CLASSNAME` (`CLASSNAME`);
