
/*
 核心拖拽框架主表
 用途：主要用于存储页面级的配置数据信息
 */
CREATE TABLE `idm` (
  `id` varchar(100) COLLATE utf8_bin NOT NULL,
  `CREATE_USERID` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人用户id',
  `CREATE_UNAME` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人姓名',
  `CREATE_DEPTID` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `CREATE_UNITID` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `LASTUPDATE_USERID` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `LASTUPDATE_UNAME` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `LASTUPDATE_DEPTID` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `LASTUPDATE_UNITID` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `LASTUPDATE_TIME` datetime DEFAULT NULL,
  `PROJECT_ID` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `CREATE_DEPTNAME` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `LASTUPDATE_UNITNAME` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `LASTUPDATE_DEPTNAME` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `IS_MODIFY` decimal(2,0) DEFAULT '-1' COMMENT '是否更新',
  `PRIORITY` decimal(2,0) DEFAULT NULL COMMENT '优先级',
  `AUTHOR_USER_TEXT` text COLLATE utf8_bin,
  `AUTHOR_USER` text COLLATE utf8_bin,
  `AUTHOR_USER_SCHEMA` text COLLATE utf8_bin,
  `CREATE_UNITNAME` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `AUTHOR_ROLE_TEXT` text COLLATE utf8_bin COMMENT '授权角色',
  `AUTHOR_ROLE` text COLLATE utf8_bin COMMENT '授权角色',
  `AUTHOR_ROLE_SCHEMA` text COLLATE utf8_bin COMMENT '授权角色',
  `AUTHOR_DEPT_TEXT` text COLLATE utf8_bin COMMENT '授权单位',
  `AUTHOR_DEPT` text COLLATE utf8_bin COMMENT '授权单位',
  `AUTHOR_DEPT_SCHEMA` text COLLATE utf8_bin COMMENT '授权单位',
  `TITLE` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `TYPE_VALUE` int(11) DEFAULT NULL,
  `TYPE_TEXT` varchar(20) COLLATE utf8_bin DEFAULT NULL,
  `ICON_URL` varchar(200) COLLATE utf8_bin DEFAULT NULL,
  `CURRENT_VERSION_TEXT` varchar(20) COLLATE utf8_bin DEFAULT NULL,
  `CURRENT_SCHEMA_TEXT` longtext COLLATE utf8_bin,
  `CURRENT_SCHEMA_PATH` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `CURRENT_AUTHOR` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `CURRENT_REMARK` varchar(500) COLLATE utf8_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC;

/*
核心框架的页面配置操作记录
用途：主要用于记录页面配置的操作记录
 */
CREATE TABLE `idm_trace` (
  `id` varchar(100) NOT NULL,
  `IDM_ID` varchar(100) DEFAULT NULL,
  `ACTIONTYPE` int(3) DEFAULT NULL,
  `PAGEID` varchar(100) DEFAULT NULL,
  `PAGEVERSION` varchar(50) DEFAULT NULL,
  `OPDATE` varchar(30) DEFAULT NULL,
  `OPTIME` varchar(30) DEFAULT NULL,
  `OPCONTENT` text,
  `PROJECT_ID` varchar(50) DEFAULT NULL,
  `CREATE_USERID` varchar(50) DEFAULT NULL,
  `CREATE_UNAME` varchar(100) DEFAULT NULL,
  `CREATE_DEPTID` varchar(50) DEFAULT NULL,
  `CREATE_UNITID` varchar(50) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `LASTUPDATE_USERID` varchar(50) DEFAULT NULL,
  `LASTUPDATE_UNAME` varchar(100) DEFAULT NULL,
  `LASTUPDATE_DEPTID` varchar(50) DEFAULT NULL,
  `LASTUPDATE_UNITID` varchar(50) DEFAULT NULL,
  `LASTUPDATE_TIME` datetime DEFAULT NULL,
  `CREATE_DEPTNAME` varchar(100) DEFAULT NULL,
  `LASTUPDATE_UNITNAME` varchar(100) DEFAULT NULL,
  `LASTUPDATE_DEPTNAME` varchar(100) DEFAULT NULL,
  `CREATE_UNITNAME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*
核心框架的页面版本历史记录表
作用：用于存储所有版本的历史数据，方便版本切换、数据恢复
*/
CREATE TABLE `idm_version` (
  `id` varchar(100) COLLATE utf8_bin NOT NULL,
  `CREATE_USERID` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人用户id',
  `CREATE_UNAME` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人姓名',
  `CREATE_DEPTID` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `CREATE_UNITID` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `LASTUPDATE_USERID` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `LASTUPDATE_UNAME` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `LASTUPDATE_DEPTID` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `LASTUPDATE_UNITID` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `LASTUPDATE_TIME` datetime DEFAULT NULL,
  `PROJECT_ID` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `CREATE_DEPTNAME` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `LASTUPDATE_UNITNAME` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `LASTUPDATE_DEPTNAME` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `CREATE_UNITNAME` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `IDM_ID` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `VERSION_TEXT` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `SCHEMA_TEXT` longtext COLLATE utf8_bin,
  `SCHEMA_PATH` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `AUTHOR` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `REMARK` varchar(500) COLLATE utf8_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC;